### ISSUE TITLE
Add yourself to this list

### ISSUE THREAD

**Issue by thekeura** [ImmediateMurderProfessionals/Random-people-being-fucking-idiots-compilation#1]
You are a failed human being

https://raw.githubusercontent.com/ImmediateMurderProfessionals/My-gd-account-is-banned-this-is-literally-1984/main/read%20this How do you think you're innocent here, L

**Comment by ImmediateMurderProfessionals** [comment]
because I've been posrting shit like this for >1Y and nobody gave a shit
My guess is that GD thought I was a bot seeing as I had >1.1K lvls on my acct

**Comment by ImmediateMurderProfessionals** [comment]
> You are a failed human being
> 
> https://raw.githubusercontent.com/ImmediateMurderProfessionals/My-gd-account-is-banned-this-is-literally-1984/main/read%20this How do you think you're innocent here, L

And besides, I am a creator! I don't want a ban! I have uploaded six rateworthy levels and am working on a 7th

**Comment by ImmediateMurderProfessionals** [comment]
Imma make a sockpuppet account, don't worry I will try to stop with the sex stuff (I'll post sex stuff somwehere else)

**Comment by ImmediateMurderProfessionals** [comment]
Update: That's not why I was banned. I was banned because H*xagon mass reported all my levels. I will make a discord account and try to get myself unbanned

**Comment by ImmediateMurderProfessionals** [comment]
n

**Comment by ImmediateMurderProfessionals** [comment]
not banned lol

**Comment by ImmediateMurderProfessionals** [comment]
> because I've been posrting shit like this for >1Y and nobody gave a shit My guess is that GD thought I was a bot seeing as I had >1.1K lvls on my acct

LOL I WAS RIGHT
(a month late but sitll)
